# Generated by Django 2.2 on 2019-04-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurerequest',
            options={'verbose_name_plural': 'Feature Requests'},
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
