# Generated by Django 2.2 on 2019-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_req', '0002_auto_20190422_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
