# Generated by Django 2.2 on 2019-04-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_req', '0003_auto_20190422_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='productionarea',
            options={'verbose_name_plural': 'Production areas'},
        ),
    ]
