# Generated by Django 2.2 on 2019-04-24 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_req', '0004_auto_20190423_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
